### ISSUE TITLE
Vignette / User Guide

### ISSUE THREAD

**Issue by benjytan88** [SCA-IRCM/SingleCellSignalR_v1#15]
Hi developers, 
This is an interesting package & I'm very interested to try it for our single-cell dataset. 
Where can I get a proper vignette or user guide? 
I could not obtain the `UsersGuide HTML` file as it only displays in raw form. 
I also could not properly render the `Rmd` file in `vignettes` as the plots are not available. 
Could you please provide assistance? 
Thank you very much.

**Comment by SCA-IRCM** [comment]
Hi,
You can go on https://github.com/SCA-IRCM/SingleCellSignalR_v1/blob/master/UsersGuide.html, then click on **download**, the raw form will be displayed and then you right-click > save as... (or Ctrl-S) to save the UsersGuide.html file.
Let me know if this works for you.
Thanks for using SingleCellSignalR.

SCA

**Comment by benjytan88** [comment]
Hi @SCA-IRCM ,
Thank you for your reply. Your suggestion works. 
I also found your package on BioConductor, so I managed to view the guide there as well. 
Thank you very much again! Looking forward to test out this wonderful package!
