### ISSUE TITLE
cell_signaling rowSums error

### ISSUE THREAD

**Issue by sylvia-science** [SCA-IRCM/SingleCellSignalR_v1#19]
I'm getting the following error when I run the cell_signaling function with the autocrine setting. So it seems to run for two cell pairs and then throws the rowSums error.

Autocrine signaling: 
Checking for cell/cell signaling:
115 interactions from 1 baseline B Cell to 1 baseline B Cell
103 interactions from 1 baseline B Cell to 1 baseline CD14+ Mono
Error in rowSums(temp) : 'x' must be an array of at least two dimensions

However, if I switch it to paracrine, it runs just fine. Why could this be?

**Comment by SCA-IRCM** [comment]
Hi,
The error came from the fact that your cluster counted only one cell. A test has been added to avoid this error to happen again. You can install **SingleCellSignalR** v1.8 and it should work fine.

Thanks for using **SingleCellSignalR**!

SCA

**Comment by sylvia-science** [comment]
Thank you! I should have noticed that it was only one cell and that was the problem.
