### ISSUE TITLE
Hot to plot interactions between two groups of cells comprising different cell types?

### ISSUE THREAD

**Issue by kaizen89** [SCA-IRCM/SingleCellSignalR_v1#2]
Hi,
Thanks for making this great tool.
I was wandering if there was a way to to plot interactions between two groups of cells comprising different cell types like in this example here where I plotted the interactions between immune and stromal cells.
Thank you
![image](https://user-images.githubusercontent.com/30392707/76171183-c2ceca00-6188-11ea-8cc8-541f846592d8.png)

**Comment by SCA-IRCM** [comment]
Hi, 
Thanks to you for using it!
I don't fully understand your question, I think you want to use the visualize() function. You'll find more details about how to use it in the User's Guide (https://github.com/SCA-IRCM/SingleCellSignalR_v1/blob/master/UsersGuide.html).
Keep me posted if you have any other question.
Thanks again.

SCA

**Comment by kaizen89** [comment]
I will try to rephrase,
Let's say I have dataset comprising immune cells and stromal cells, the cluster 1,2 and 3 are different immune cell populations and the clusters 4,5 and 6 are different stromal cell populations. What I want is to focus the analysis of the pairs between each of the immune cells and each of the stromal cells. Is this something that is currently possible or should I specifiy each of the combinations (1,4), (1,5), (1,6), (2,4), (2,5), (2,6) etc. The problem is that I have 100 possible combinations. Hope it is more clear now.

**Comment by SCA-IRCM** [comment]
Once you have the _signal_ list (output of the **cell_signallling()** function), you can select the elements you want the **visualize()** function to plot. There is no systematic way to do it but you can use the names of the _signal_ list. For example `signal[grepl("immune", names(signal))]` will select only the elements of _signal_ that involve immune cells.

**Comment by SCA-IRCM** [comment]
Hope this helps. 
:)
