### ISSUE TITLE
bulk RNA seq 

### ISSUE THREAD

**Issue by imranlahmar** [SCA-IRCM/SingleCellSignalR_v1#23]
Hello, 

Is it possible to use this package using as input data from bulk rna seq instead of scRNA-seq ? 
Thank you for your help.

Imran Lahmar.
Ph.D student.

**Comment by SCA-IRCM** [comment]
Hello,

The package is designed for single-cell RNA seq data, however a bulk version is at work and will be available soon.
Thank you for your question.

SCA
