### ISSUE TITLE
cannot allocate vector of size 180.0 Mb

### ISSUE THREAD

**Issue by torumatsuura** [SCA-IRCM/SingleCellSignalR_v1#24]
Dear whom it may concern,

When I analyze my data, R says like below:
> clust <- clustering(data = data,n = 10, method = "simlr")
Estimating the number of clusters
Error: cannot allocate vector of size 180.0 Mb

Should I reduce the size of my data? If so, I like to know how to reduce the size.
Any help would be appreciated.
Best regards,

Toru

**Comment by torumatsuura** [comment]
In addition to the comment attached in previous message,
R says like below:
In addition: Warning messages:
1: In for (i in 1L:d2) { :
  closing unused connection 10 (<-DESKTOP-GDM6FQI:11473)
2: In for (i in 1L:d2) { :
  closing unused connection 9 (<-DESKTOP-GDM6FQI:11473)
3: In for (i in 1L:d2) { :
  closing unused connection 8 (<-DESKTOP-GDM6FQI:11473)
4: In for (i in 1L:d2) { :
  closing unused connection 7 (<-DESKTOP-GDM6FQI:11473)
5: In for (i in 1L:d2) { :
  closing unused connection 6 (<-DESKTOP-GDM6FQI:11473)
6: In for (i in 1L:d2) { :
  closing unused connection 5 (<-DESKTOP-GDM6FQI:11473)
7: In for (i in 1L:d2) { :
  closing unused connection 4 (<-DESKTOP-GDM6FQI:11473)

**Comment by torumatsuura** [comment]
Increasing memory limits (16000->100000) makes the program to work.
memory.limit(size=100000)

**Comment by SCA-IRCM** [comment]
Hi,
It seems that you solved your issue!
Well done.
Don't hesitate to contact me if you have any other question.

Thanks for using **SingleCellSignalR**!

SCA

**Comment by torumatsuura** [comment]
Thanks.
