### ISSUE TITLE
Questions regarding Seurat and SingleCellSignalR integration

### ISSUE THREAD

**Issue by singcell** [SCA-IRCM/SingleCellSignalR_v1#5]
I am using SingleCellSignalR with Seurat tool as directed in **Supplementary Box 2** of your publication. In the box 2 you have shown steps until visualization. 
Next I wanted to perform cell classification using cell_classifier function. However, I am not sure how I can integrate cell_classifier with the Seurat ouptput i.e "data = data.frame(pbmc[["RNA"]]@ data) ". 
DO I need to run `clustering(data = data,n = 10, method = "simlr")` after retrieving the results of the preprocessing from the Seurat object followed by Cell classification and Cluster analysis.

Thank you

**Comment by SCA-IRCM** [comment]
Hello,
You can use the visualization function (see the User's Guide: https://github.com/SCA-IRCM/SingleCellSignalR_v1/blob/master/UsersGuide.html for more details).
You can also use the cell_classifier function with the Seurat output counts data frame, see the details of this function for proper use.
Thank you for using SingleCellSignalR.

SCA

**Comment by singcell** [comment]
@SCA-IRCM Thank you for your reply.
