### ISSUE TITLE
Failed running intra_network

### ISSUE THREAD

**Issue by DouberZ** [SCA-IRCM/SingleCellSignalR_v1#6]
Hi, I attempted running intra_network, however, following error information returned.

Error in as.igraph.vs(graph, from) : Invalid vertex names
4.
stop("Invalid vertex names")
3.
as.igraph.vs(graph, from)
2.
shortest_paths(g.net.tmp, receptors, V(g.net.tmp))
1.
intra_network(goi = "Egfr", coi = "N1", data = input, genes = rownames(input), cluster = as.numeric(Idents(temp)), c.names = cnames, species = "mus musculus", write = FALSE, signal = signal)

Before, I run inter_network successfully with this:
inter.net <- inter_network(data = input, genes = rownames(input), cluster = as.numeric(Idents(temp)), signal = signal, c.names = cnames, species = "mus musculus", write = FALSE)

Looking forward to your reply.

Bo

**Comment by SCA-IRCM** [comment]
Hi,
The problem is fixed now. Make sure you re-install version 0.0.1.6 of the package and it will work.
Thank's for bringing this up.

SCA

**Comment by DouberZ** [comment]
Thank you very much. Everything goes well now.
