### ISSUE TITLE
Error while clustering

### ISSUE THREAD

**Issue by singcell** [SCA-IRCM/SingleCellSignalR_v1#7]
I am using matrix file generated by  'Read10x' function to input in `data_prepare`.
I get following `data_prepare` output:

>  data <- data_prepare(file=file, most.variables = 2000,write = TRUE)
log-Normalization
15200 genes
14267 cells
Zero rate = 91.2%
**Warning message:**
In fread(file, data.table = FALSE) :
  Detected 14267 column names but the data has 14268 columns (i.e. invalid file). Added 1 extra default column name for the first column which is guessed to be row names or an index. Use setnames() afterwards if this guess is not correct, or fix the file write command that created the file to create a valid file.

looks like previous step log-normalized  and If I overlook this warning message and go over to `clustering` command, I get following Error:

>clust <- clustering(data = data, n = 10, method = "simlr")
Estimating the number of clusters
**Error in x^2 : non-numeric argument to binary operator**

Would it be possible for you to diagnose the problem?

Thank you.

**Comment by SCA-IRCM** [comment]
Hi,
I advise you not to combine the pre-processing steps from different tools (Seurat and SingleCellSignalR). If you want to use Seurat for pre-processing, do the log normalization steps before extracting the counts matrix (see https://github.com/SCA-IRCM/Demo/blob/master/example_seurat.R) to feed the clustering function of SingleCellSignalR.
Thank you for using SingleCellSignalR.

SCA
