### ISSUE TITLE
Formatting and plotting non-clustered Data

### ISSUE THREAD

**Issue by oh111** [SCA-IRCM/SingleCellSignalR_v1#8]
Hi!
I was wondering if the package had the capability of the following: 
1. Adjusting the formatting to label the clusters based of pre-set labels and other formatting (changing colors, thickness of arrows etc)
2. Seeing cell signaling not based off clustering from the previous analyses (umap or tsne), but rather cell identity (without using cell markers). For instance if I have three cell lines-- control, cell 1 and cell2, can I use these in the signal analysis. 

Thanks!

**Comment by SCA-IRCM** [comment]
Hi,
1. No, the visualization parameters are not accessible in the _visualize()_ function. However it could be a good idea in a further release. :)
2. Yes, for that you just need to create a cluster vector of your own:
`cluster = c(rep(1, length(control.counts)),rep(2, length(cell1.counts)),rep(3, length(cell2.counts)))`

Thanks for using SingleCellSignalR.

SCA
